# Site settings
title: Diego Di Carlo
email: diego.di-carlo@inria.fr
description: > # this means to ignore newlines until "baseurl:"
  My name is Diego Di Carlo and this is my site. You can find stuff about
  my music, my research and randomness.
interest: >
  - Breakcore, Technical Death, Post and Avangarde
  - Whale, Chelicerata, and Periophthalmus
  - Lovercraft's and King's universe

motto: >
   MeeeeeeeegaDspMachineLearningALotOfConvolutionFFTLikeItWasRainingSubitoCiao

short_bio:
  I am a PhD candidate in Audio Signal Processing and Machine Learning<br/>
  at INRIA in the [team PANAMA](https://team.inria.fr/panama/) in France.<br/>
  Under the supervision of [Antoine Deleforge](https://members.loria.fr/ADeleforge/)
  and [Nancy Bertin](https://people.irisa.fr/Nancy.Bertin/en), <br/>
  I am currently working on estimating early acoustic echoes for audio inverse problem.

address:
  - building: INRIA Rennes Bretagne Atlantique
  - street: Campus de Beaulieu 263 Avenue Général Leclerc
  - city: 35042 Rennes Cedex – France


# stuff for the website

baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chutlhu
github_username:  chutlhu
linkedin_username: diegodicarlo
gscholar_username: TZLUhuIAAAAJ
avatar: images/avatar.jpg
logo_header: images/logo-diego-bordered.png
logo_footer: images/logo-diego-grey.png

# Build settings
markdown: CommonMarkGhPages

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

paginate: 3
paginate_path: "blog/page:num"

plugins: [jekyll-paginate]

socials_fa:
  - icon: envelope
    url: mailto:diego.di-carlo@inria.fr
  - icon: github
    url: http://github.com/chutlhu
  - icon: linkedin
    url: http://www.linkedin.com/in/diego-di-carlo-b69460138/
socials_ai:
  - icon: google-scholar
    url: https://scholar.google.fr/citations?user=TZLUhuIAAAAJ


# I want to have a collection of projects
collections:
  projects:
    output: true
  pages:
    output: true
  musics:
    output: true


exclude: ['_old']