# Site settings
title: "Robin Scheibler"
logo: logo_robin.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: fakufaku@gmail.com
description: > # this means to ignore newlines until "url:"
  Robin Scheibler is a graduate student at the <a href='http://lcav.epfl.ch'>Audiovisual 
  Communications Laboratory</a> of <a href='http://www.epfl.ch'>EPFL</a> in Lausanne, 
  Switzerland. He likes algorithms, electronics, and open data.
url: "http://robinscheibler.org" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: fakufakurevenge
github_username:  fakufaku

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
