# Site settings
title: Robin Scheibler
email: robin.scheibler@epfl.ch
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: fakufakurevenge
github_username:  fakufaku
linkedin_username: robinscheibler

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"

gems: [jekyll-paginate]

socials:
  - icon: envelope
    url: mailto:robin[dot]scheibler[at]gmail[dot]com
  - icon: github
    url: http://github.com/fakufaku
  - icon: twitter
    url: http://www.twitter.com/fakufakurevenge
  - icon: linkedin
    url: http://www.linkedin.com/in/robinscheibler

# I want to have a collection of projects
collections:
  projects:
    output: true
