# Site settings
title: Diego Di Carlo
email: diego.di-carlo@inria.fr
description: > # this means to ignore newlines until "baseurl:"
  My name is Diego Di Carlo and this is my site. You can find stuff about
  my music, my research and randomness.

interest: >
  - Breakcore, Technical Death, Post and Avangarde
  - Whale, Chelicerata, and Periophthalmus
  - Lovercraft's and King's universe

motto: >
  Monochromatic sky is overrated - better when it supercollides with the world and glitches arise.<br>
  Even better when Tiepolo's clouds spit on it.<br>
  ... "Ufourk!"

short_bio: >
  I am a **postodoctoral researcher** at in the [Sound Scene Understanding Team](http://www.riken.jp/en/research/labs/aip/goalorient_tech/sound_scene_understand/),
  [Center for Advanced Intelligence Project (AIP)](https://www.riken.jp/en/research/labs/aip/index.html), [RIKEN](http://www.riken.jp/en/) and
  a visiting researcher in the [Speech and Audio Processing Group](http://sap.ist.i.kyoto-u.ac.jp/EN/), [Kyoto University](https://www.kyoto-u.ac.jp/en/).

short_bio2: >
  I am a **postodoctoral researcher** at in the [Sound Scene Understanding Team](http://www.riken.jp/en/research/labs/aip/goalorient_tech/sound_scene_understand/),
  [Center for Advanced Intelligence Project (AIP)](https://www.riken.jp/en/research/labs/aip/index.html), [RIKEN](http://www.riken.jp/en/) and
  a visiting researcher in the [Speech and Audio Processing Group](http://sap.ist.i.kyoto-u.ac.jp/EN/), [Kyoto University](https://www.kyoto-u.ac.jp/en/).

address:
  - building: INRIA Rennes Bretagne Atlantique
  - street: Campus de Beaulieu 263 Avenue Général Leclerc
  - city: 35042 Rennes Cedex – France

# stuff for the website
tbc: "Hic sunt Dracones"

baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chutlhu
github_username:  chutlhu
linkedin_username: diegodicarlo
gscholar_username: TZLUhuIAAAAJ
avatar: images/avatar.jpg
logo_header: images/logo-diego-bordered.png
logo_footer: images/logo-diego-grey.png

# Build settings
# markdown: CommonMarkGhPages
markdown: GFM

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

paginate: 8
paginate_path: "blog/page:num"

plugins:
  - jekyll-paginate
  - jekyll-spaceship

socials_fa:
  - icon: envelope
    url: mailto:diego[dot]dicarlo89[at]gmail.com
  - icon: github
    url: http://github.com/chutlhu
  - icon: linkedin
    url: http://www.linkedin.com/in/diego-di-carlo-b69460138/
socials_ai:
  - icon: google-scholar
    url: https://scholar.google.fr/citations?user=TZLUhuIAAAAJ


# I want to have a collection of projects
collections:
  projects:
    output: true
  pages:
    output: true
  musics:
    output: true


exclude:
  - '_old'
  - 'scripts/venv/'
