# Site settings
title: Diego Di Carlo
email: diego.di-carlo@inria.fr
description: > # this means to ignore newlines until "baseurl:"
  My name is Diego Di Carlo and this is my site. You can find stuff about
  the research and projects I do.
tldr_bio: >
  Avangarde. Post. Currently Ph.D. Student.
  With a wholehearted taste for Brutal Death Metal, Spiders and Cthulhu..
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chutlhu
github_username:  chutlhu
linkedin_username: diegodicarlo
avatar: images/avatar.jpg
logo_header: images/logo-diego-bordered.png
logo_footer: images/logo-diego-grey.png

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"

plugins: [jekyll-paginate]

socials:
  - icon: envelope
    url: mailto:diego[dot]di-carlo[at]inria[dot]fr
  - icon: github
    url: http://github.com/chutlhu
  - icon: linkedin
    url: http://www.linkedin.com/in/diego-di-carlo-b69460138/

# I want to have a collection of projects
collections:
  projects:
    output: true
  pages:
    output: true
  musics:
    output: true
